version: 2
jobs:
  eslint:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
=      - run: npm install
      - save_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
  stylelint:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
        keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
      - run: npm run stylelint
  build:
    - restore_cache:
      keys:
        - v1-npm-deps-{{ checksum "package.json" }}
    - run: npm install
    - save_cache:
      keys:
        - v1-npm-deps-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules
    - run: npm run build
  deploy:
    - run: npm run deploy:ci
workflows:
  version: 2
  linting:
    jobs:
      - eslint
      - stylelint
  build-and-deploy:
    - build
    - deploy:
        requires:
          - build
        filters:
          tags:
            only: /^v.*/
